name: CI-users

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: ezpmlnt
        uses: hiwane/ezpmlnt
        run: |
          ls
          echo ezpmnt
          ls -l ezpmlnt
          sh -c "! ./ezpmlnt/html5.sh ./ng.html"
          ./ezpmlnt/html5.sh ./ok.html




